services:
  neo4j:
    image: neo4j:5.19
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/G7q!rX#9Lp@eZ1vK
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  extractor:
    build: .
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=G7q!rX#9Lp@eZ1vK
      # Configurações do ambiente
      - PYTHONUNBUFFERED=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Configurações GitHub
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO:-leds-conectafapes/*}
      # Cache settings
      - CACHE_TYPE=duckdb
    volumes:
      # Monte o socket do Docker para permitir acesso ao Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
      # Monte um volume para dados persistentes
      - ./data:/app/data
      # Volume para cache PyAirbyte
      - airbyte_cache:/tmp/airbyte
    extra_hosts:
      # Para acessar serviços na máquina host
      - "host.docker.internal:host-gateway"

volumes:
  neo4j_data:
  airbyte_cache: