services:
  extractor:
    build: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - REPOSITORIES=${REPOSITORIES}
      - ORGANIZATION_ID=${ORGANIZATION_ID}
      - ORGANIZATION=${ORGANIZATION}
      - DB_HOST_LOCAL=${DB_HOST_LOCAL}
      - DB_PORT_LOCAL=${DB_PORT_LOCAL}
      - DB_USER_LOCAL=${DB_USER_LOCAL}
      - DB_PASSWORD_LOCAL=${DB_PASSWORD_LOCAL}
      - DB_NAME_LOCAL=${DB_NAME_LOCAL}
      - LOG_DIR=/logs
    networks:
      - theband-network
    volumes:
      - ./output:/data
      - ./logs:/logs
 
networks:
  theband-network:
    external: true


