services:
  extractor:
    build: .  
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - REPOSITORIES=${REPOSITORIES}
    networks:
      - theband-network

networks:
  theband-network:
    external: true
